### PR TITLE
Fix for Coverity 1093690: Resource leak

### PR DESCRIPTION
**Pull request by asarium**
This introduces a move constructor for CJumpNode to handle freeing resources.

### CODE REVIEW

**Comment by asarium** [comment]
I haven't implemented the move semantics completely. I added a move operator=, hopefully the GCC STL will detect that and use it instead of trying to use the non-existent copy-constructor.

**Comment by niffiwan** [comment]
I'm not sure what happened to my previous comment? Anyway, after some more digging and help from MageKing17, I think the issue is in our custom STL allocator, it doesn't seem to have anything to deal with move ctor/assignment operations, and it's deliberately trying to use the copy-ctor See SCP_vm_allocator::construct in code/globalincs/vmallocator.h.

At least, that's my best guess at the moment, I'm still trying to wrap my head around how the custom allocator works.

**Comment by niffiwan** [comment]
also note; compiles & runs fine when you get rid of the custom allocator and just use the #defined functions :/

**Comment by asarium** [comment]
I think your comment is missing because commented on a commit that doesn't exist anymore, apparently GitHub can't handle that.

I'll take a look at the allocator and try to fix the problem.

**Comment by asarium** [comment]
[It appears](http://stackoverflow.com/a/8864895) that move constructors must be `noexcept` in order to be used used by a vector.
That would explain why it compiles without issues in Visual Studio as that currently doesn't support `noexcept` but gcc and clang do support it so adding noexcept to the move constructor and assignment operator could solve the problem but it would need to be hidden behind a macro as VS doesn't recognize that keyword.

**Comment by niffiwan** [comment]
Thanks for the suggestion, however I added noexcept (& fixed a typo) and it's still got the same error:

```
diff --git a/code/jumpnode/jumpnode.cpp b/code/jumpnode/jumpnode.cpp
index fe14457..adbd2a3 100644
--- a/code/jumpnode/jumpnode.cpp
+++ b/code/jumpnode/jumpnode.cpp
@@ -55,7 +55,7 @@ CJumpNode::CJumpNode(vec3d *position) : m_radius(0.0f), m_modelnum(-1), m_objnum
     m_objnum = obj_create(OBJ_JUMP_NODE, -1, -1, NULL, &m_pos, m_radius, OF_RENDERS);
 }
 
-CJumpNode::CJumpNode(CJumpNode&& other)
+CJumpNode::CJumpNode(CJumpNode&& other) noexcept
        : m_radius(other.m_radius), m_modelnum(other.m_modelnum), m_objnum(other.m_objnum), m_flags(other.m_flags)
 {
        other.m_radius = 0.0f;
@@ -69,7 +69,7 @@ CJumpNode::CJumpNode(CJumpNode&& other)
        strcpy_s(m_name, other.m_name);
 }
 
-CJumpNode& CJumpNode::operator=(CJumpNode&& other)
+CJumpNode& CJumpNode::operator=(CJumpNode&& other) noexcept
 {
        if (this != &other)
        {
diff --git a/code/jumpnode/jumpnode.h b/code/jumpnode/jumpnode.h
index a4375af..54df95a 100644
--- a/code/jumpnode/jumpnode.h
+++ b/code/jumpnode/jumpnode.h
@@ -42,12 +42,12 @@ public:
     //Constructors
     CJumpNode();
     CJumpNode(vec3d *position);
-       CJumpNode(CJumpNode&& other);
+       CJumpNode(CJumpNode&& other) noexcept;
 
        CJumpNode(const CJumpNode&) = delete;
        CJumpNode& operator=(const CJumpNode&) = delete;
 
-       CJumpNode& CJumpNode::operator=(CJumpNode&&);
+       CJumpNode& operator=(CJumpNode&&) noexcept;
     
     //Destructor
     ~CJumpNode();
```

and the error for reference:
```
In file included from ./globalincs/pstypes.h:681:0,
                 from ./ai/ai.h:15,
                 from ./mission/missionparse.h:14,
                 from mission/missionparse.cpp:24:
./globalincs/vmallocator.h: In instantiation of ‘void SCP_vm_allocator<T>::construct(SCP_vm_allocator<T>::pointer, const T&) [with T = std::_List_node<CJumpNode>; SCP_vm_allocator<T>::pointer = std::_List_node<CJumpNode>*]’:
/usr/include/c++/4.8/bits/stl_list.h:505:8:   required from ‘std::list<_Tp, _Alloc>::_Node* std::list<_Tp, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {CJumpNode}; _Tp = CJumpNode; _Alloc = SCP_vm_allocator<CJumpNode>; std::list<_Tp, _Alloc>::_Node = std::_List_node<CJumpNode>]’
/usr/include/c++/4.8/bits/stl_list.h:1561:63:   required from ‘void std::list<_Tp, _Alloc>::_M_insert(std::list<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {CJumpNode}; _Tp = CJumpNode; _Alloc = SCP_vm_allocator<CJumpNode>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<CJumpNode>]’
/usr/include/c++/4.8/bits/stl_list.h:1021:9:   required from ‘void std::list<_Tp, _Alloc>::push_back(std::list<_Tp, _Alloc>::value_type&&) [with _Tp = CJumpNode; _Alloc = SCP_vm_allocator<CJumpNode>; std::list<_Tp, _Alloc>::value_type = CJumpNode]’
mission/missionparse.cpp:4965:38:   required from here
./globalincs/vmallocator.h:59:3: error: use of deleted function ‘std::_List_node<CJumpNode>::_List_node(const std::_List_node<CJumpNode>&)’
   ::new (p) T(value);
   ^
In file included from /usr/include/c++/4.8/list:63:0,
                 from ./globalincs/vmallocator.h:7,
                 from ./globalincs/pstypes.h:681,
                 from ./ai/ai.h:15,
                 from ./mission/missionparse.h:14,
                 from mission/missionparse.cpp:24:
/usr/include/c++/4.8/bits/stl_list.h:106:12: note: ‘std::_List_node<CJumpNode>::_List_node(const std::_List_node<CJumpNode>&)’ is implicitly deleted because the default definition would be ill-formed:
     struct _List_node : public __detail::_List_node_base
            ^
/usr/include/c++/4.8/bits/stl_list.h:106:12: error: use of deleted function ‘CJumpNode::CJumpNode(const CJumpNode&)’
In file included from mission/missionparse.cpp:54:0:
./jumpnode/jumpnode.h:47:2: error: declared here
  CJumpNode(const CJumpNode&) = delete;
  ^
make[1]: *** [mission/missionparse.o] Error 1
```

**Comment by asarium** [comment]
Hmm, [cppreference](http://en.cppreference.com/w/cpp/concept/Allocator) says that `construct` and `destruct` are optional. Maybe removing that will use a default version that handles move constructors correctly.
I'll try that later in my VM.

**Comment by niffiwan** [comment]
I've also found that issue #49 is fixed by removing the custom allocator, so there's probably a larger issue re: c++11 support here.

**Comment by asarium** [comment]
I managed to get FSO to compile again by introducing an overload for construct: https://gist.github.com/asarium/345f8f1b84d2e5b93a2a

If it compiles for you I will work on a solution to also make it available to older compiler versions that don't have support for variadic templates.

**Comment by niffiwan** [comment]
this is great! Compiles and fixes issue #49 :+1:

**Comment by asarium** [comment]
How well are variadic templates supported by GCC and Clang?
I would add an #ifdef check for every VS version >= 2013 but given the wide spread support for C++11 on linux disabling that code doesn't seem necessary.

**Comment by niffiwan** [comment]
according to [this website](http://wiki.apache.org/stdcxx/C++0xCompilerSupport) GCC supports variadic templates since 4.4 and Clang since 2.9 so I wouldn't worry about adding #ifdefs for them. Well, unless you want to wrap them in #HAVE_CXX11.

**Comment by MageKing17** [comment]
What's the point in allowing vmallocator.h to compile on older version of Visual Studio if they're just going to run into the same problem of CJumpNode not having a copy constructor?

**Comment by Goober5000** [comment]
I just tried compiling a fresh checkout from git on Visual Studio 2005 and it compiled successfully.

**Comment by MageKing17** [comment]
Yes, but does the resultant build still crash in The Romans Blunder?

**Comment by niffiwan** [comment]
@Goober5000 which branch did you build from?  Master on Linux will currently crash in The Romans Blunder when the Iceni jumps out, the branch on Linux works fine.  It'd be good to know what Windows does in both situations.

**Comment by asarium** [comment]
@MageKing17: VS happily compiles the code without the vmalloc changes, their `vector` implementation probably doesn't use the `construct` function of the allocator.
Variadic templates are only supported since VS 2013 and I didn't want to break compilation on VS >= 2010 only for this.

@Goober5000: I am a bit puzzled that it compiles in VS 2005 as it uses move semantics and operators. Does it actually run?

**Comment by MageKing17** [comment]
I can guarantee that Visual Studio's std::vector implementation goes through our construct function, at least in VS 2013. It's possible that it didn't on older versions, though.

**Comment by asarium** [comment]
Then I have no idea why the first version compiled on VS2013. Can somebody test this with VS2012 or 2010?

**Comment by MageKing17** [comment]
It's not a compile-time problem, is it? The problem crops up when the vector tries to resize and discovers that it can't use the move constructor and the copy constructor is deleted.

**Comment by asarium** [comment]
It must be a compile-time problem. There is no overload resolution as runtime.

**Comment by MageKing17** [comment]
Well, it being a compile-time problem in gcc doesn't necessarily make it a compile-time problem in Visual Studio, what with different standard library implementations...

**Comment by asarium** [comment]
The standard library can't be that different. C++ doesn't have reflection so the implementation can only decide which constructor to use at compile time.
That's the whole point of deleted constructors and operators, they make sure that a compile time error is generated if anyone tries to use them.

**Comment by MageKing17** [comment]
... Yeah, I got nothing. By all rights, Visual Studio's behavior there doesn't make sense.

**Comment by asarium** [comment]
I just looked at the library code for vector. If the `Allocator` doesn't have the required function overload it uses a default version which just forwards the arguments to the constructor.
Now we only have to check VS2012 and 2010 but they probably have a similar solution.

**Comment by Goober5000** [comment]
@niffiwan @asarium Sorry, should have specified that I checked out and compiled master.  Not only does the build run, but it works fine on The Roman's Blunder.  The Iceni jumps out and no crash occurs.

However, when I tried applying the changes from this issue's diff, it didn't compile at all.  It complained about the double ampersand at the end of CJumpNode&&.  (This is a C++11 addition.)

**Comment by niffiwan** [comment]
Do we know who has 2012 & 2010 to check? And is that the only thing we're waiting on for this PR?

**Comment by asarium** [comment]
I think VS 2010 and 2012 compatibility is the only thing that hasn't been tested yet. If no one actually uses those compilers we could just merge this,

**Comment by chief1983** [comment]
I don't have any reason to use them for normal use, but I do have them and can check later, maybe this morning during my oil change appointment I can vnc in and give it a check.

**Comment by chief1983** [comment]
Batch building SSE2 debug and release Fred2 and FS2 now, in  VS2010.  I do have multiple VS versions installed alongside one another though, so I don't know how to be 100% sure VS2010 is sticking with only SDKs and libraries it provided.  Although as I type this I'm seeing errors fly by in the console.

**Comment by chief1983** [comment]
http://pastebin.com/u6Z0BEfY  VS2010 error report

**Comment by asarium** [comment]
Apparently VS 2010 doesn't like `=delete` but everything else seems to work. I'll make the copy constructor and assignment operator private which should fix this issue.

**Comment by chief1983** [comment]
Still some errors.
```
Error	1	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	C:\Code\fs2_open_git\code\globalincs\vmallocator.h	59	1	code
Error	2	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	59	1	code
Warning	3	warning C4701: potentially uninitialized local variable 'firepoint_list' used	c:\code\fs2_open_git\code\ship\ship.cpp	10459	1	code
Error	4	error LNK1181: cannot open input file 'C:\Code\fs2_open_git\projects\MSVC_2010\Debug\code.lib'	C:\Code\fs2_open_git\projects\MSVC_2010\LINK	Freespace2
Error	5	error LNK1104: cannot open file 'C:\Code\fs2_open_git\projects\MSVC_2010\Debug\code.lib'	C:\Code\fs2_open_git\projects\MSVC_2010\LINK	Freespace2
Error	6	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	C:\Code\fs2_open_git\code\globalincs\vmallocator.h	59	1	Fred2
Error	7	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	59	1	Fred2
Warning	8	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\initialstatus.cpp	851	1	Fred2
Warning	9	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\asteroideditordlg.cpp	443	1	Fred2
```
A very long error from the Output tab:
```
../../code\globalincs/vmallocator.h(59): error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'
          ../../code\jumpnode/jumpnode.h(42) : see declaration of 'CJumpNode::CJumpNode'
          ../../code\jumpnode/jumpnode.h(30) : see declaration of 'CJumpNode'
          ../../code\globalincs/vmallocator.h(58) : while compiling class template member function 'void SCP_vm_allocator<T>::construct(CJumpNode *,const T &)'
          with
          [
              T=CJumpNode
          ]
          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\list(418) : see reference to class template instantiation 'SCP_vm_allocator<T>' being compiled
          with
          [
              T=CJumpNode
          ]
          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\list(476) : see reference to class template instantiation 'std::_List_nod<_Ty,_Alloc>' being compiled
          with
          [
              _Ty=CJumpNode,
              _Alloc=SCP_vm_allocator<CJumpNode>
          ]
          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\list(580) : see reference to class template instantiation 'std::_List_val<_Ty,_Alloc>' being compiled
          with
          [
              _Ty=CJumpNode,
              _Alloc=SCP_vm_allocator<CJumpNode>
          ]
          ../../code\globalincs/vmallocator.h(137) : see reference to class template instantiation 'std::list<_Ty,_Ax>' being compiled
          with
          [
              _Ty=CJumpNode,
              _Ax=SCP_vm_allocator<CJumpNode>
          ]
          ../../code\jumpnode/jumpnode.h(79) : see reference to class template instantiation 'SCP_list<T>' being compiled
          with
          [
              T=CJumpNode
          ]
```

**Comment by asarium** [comment]
:rage: I added an overload for construct which should handle move constructors but nothing else. Hopefully that works...

**Comment by chief1983** [comment]
Ok, I hit rebuild this time.  Still got some errors.
```
Warning	1	warning C4701: potentially uninitialized local variable 'firepoint_list' used	c:\code\fs2_open_git\code\ship\ship.cpp	10459	1	code
Error	2	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	59	1	code
Warning	3	warning C4018: '<' : signed/unsigned mismatch	c:\code\fs2_open_git\code\hud\hudshield.cpp	568	1	code
Warning	4	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\graphics\gropenglbmpman.cpp	281	1	code
Warning	5	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\graphics\gropenglbmpman.cpp	407	1	code
Warning	6	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	c:\code\fs2_open_git\code\graphics\generic.cpp	26	1	code
Warning	7	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	c:\code\fs2_open_git\code\graphics\generic.cpp	31	1	code
Warning	8	warning C4005: 'MAKEFOURCC' : macro redefinition	c:\program files (x86)\microsoft sdks\windows\v7.0a\include\mmsystem.h	164	1	code
Warning	9	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\bmpman\bmpman.cpp	1990	1	code
Warning	10	warning C4505: 'bm_convert_color_index_to_BGR' : unreferenced local function has been removed	c:\code\fs2_open_git\code\bmpman\bmpman.cpp	125	1	code
Error	11	error LNK1104: cannot open file 'C:\Code\fs2_open_git\projects\MSVC_2010\Debug SSE2\code.lib'	C:\Code\fs2_open_git\projects\MSVC_2010\LINK	Freespace2
Error	12	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	59	1	Fred2
Warning	13	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\initialstatus.cpp	851	1	Fred2
Warning	14	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\asteroideditordlg.cpp	443	1	Fred2
```
At this point, I'm wondering if I have a compiler or SDK conflict with another version I have installed.  I did install them in increasing order though, so it's not like 2010 would be using an SDK from 2008 I wouldn't think.

**Comment by asarium** [comment]
Doesn't VS2010 has a project setting for the used toolset?

I added another commit which removes the old `construct` function. That should force the compiler to use the template function and if the vector implementation actually uses move constructors correctly it should work this way.
If it doesn't them I'm out of ideas.

**Comment by chief1983** [comment]
I don't work with the VS GUIs that often, wouldn't know where to look for that, but I saw some config strings in use like VCBuildDir.  Also, any logs seemed to indicate it was working with tools in the VS 10.0 folder, which would be 2010 specific.  I was going to see if it worked this morning but my home computer crashed while using VNC, before I could pull up the results, so I'll have to find out if it worked this evening.

**Comment by chief1983** [comment]
Ok, still having the error about "cannot access private member declared in class 'CJumpNode'".

**Comment by asarium** [comment]
Is there a more detailed error message?
It should contain where the allocator tries to use the copy constructor which might help fixing this issue.

**Comment by chief1983** [comment]
Ok let me copy the whole error output again, harder to do over VNC

**Comment by chief1983** [comment]
Full log output again:
```
Warning	1	warning C4701: potentially uninitialized local variable 'firepoint_list' used	c:\code\fs2_open_git\code\ship\ship.cpp	10459	1	code
Error	2	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	67	1	code
Warning	3	warning C4018: '<' : signed/unsigned mismatch	c:\code\fs2_open_git\code\hud\hudshield.cpp	568	1	code
Warning	4	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\graphics\gropenglbmpman.cpp	281	1	code
Warning	5	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\graphics\gropenglbmpman.cpp	407	1	code
Warning	6	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	c:\code\fs2_open_git\code\graphics\generic.cpp	26	1	code
Warning	7	warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance warning)	c:\code\fs2_open_git\code\graphics\generic.cpp	31	1	code
Warning	8	warning C4005: 'MAKEFOURCC' : macro redefinition	c:\program files (x86)\microsoft sdks\windows\v7.0a\include\mmsystem.h	164	1	code
Warning	9	warning C4244: '=' : conversion from 'BM_TYPE' to 'ubyte', possible loss of data	c:\code\fs2_open_git\code\bmpman\bmpman.cpp	1990	1	code
Warning	10	warning C4505: 'bm_convert_color_index_to_BGR' : unreferenced local function has been removed	c:\code\fs2_open_git\code\bmpman\bmpman.cpp	125	1	code
Error	11	error LNK1104: cannot open file 'C:\Code\fs2_open_git\projects\MSVC_2010\Debug SSE2\code.lib'	C:\Code\fs2_open_git\projects\MSVC_2010\LINK	Freespace2
Error	12	error C2248: 'CJumpNode::CJumpNode' : cannot access private member declared in class 'CJumpNode'	c:\code\fs2_open_git\code\globalincs\vmallocator.h	67	1	Fred2
Warning	13	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\initialstatus.cpp	851	1	Fred2
Warning	14	warning C4245: 'argument' : conversion from 'int' to 'DWORD_PTR', signed/unsigned mismatch	c:\code\fs2_open_git\code\fred2\asteroideditordlg.cpp	443	1	Fred2
```

**Comment by asarium** [comment]
I have absolutely no idea why that is breaking.
Does anybody even use VS2010? If not then we can just forget about it and only support later versions.

**Comment by chief1983** [comment]
Beats me.  You guys asked about it, I just said I could test it.  That's a question for the forums though; going from 8 supported Windows projects to 3 overnight :p

I was under the impression that during the discussion about C++11, VS2010 was supposed to be compatible with the intended planned features we wanted to use, and I feel like one or two coders were on it.  Maybe fubar or karajorma?

**Comment by The-E** [comment]
VS2010 is kind of an outlier. Its compiler may not support features we want to use, but it's possible (and rather simple, I might add) to install the clang compiler instead.

**Comment by chief1983** [comment]
Guess I won't even bother trying to get VS2008 to compile either then, at this point.  Besides VC6 it's the oldest one I have installed.  Wasn't the reason we hoped to maintain VS2010 support because it's the last one that actually runs on XP?  I guess if the clang compiler can cover that situation that'll work, but we should at least document that as the only really supported method left for compiling on XP.

**Comment by chief1983** [comment]
Also, the free Windows VMs for VirtualBox are a way that any dev could install an additional compiler in a clean environment if they'd like to experiment themselves.  http://dev.modern.ie/tools/vms/#downloads

Visual Studio Express 2010 ISO  (no MSDN account required to download) http://go.microsoft.com/?linkid=9709969

Set up the machine, install the IDE, take a snapshot, and you can fire up that snapshot any time you want to test 2010, from Linux, OS X, Win7, etc.

**Comment by MageKing17** [comment]
Does VS 2010 compile if you remove SCP_vm_allocator completely (e.g. change vmallocator.h:40 to "#if 0")?

**Comment by chief1983** [comment]
I'll test that after I finish seeing if #52 compiles as-is on 2010 now.

**Comment by chief1983** [comment]
It does compile if I do that.

**Comment by chief1983** [comment]
It also created an 'ipch' folder alongside the Debug SSE2 folder in the project directory, never seen that one before.

**Comment by niffiwan** [comment]
Assuming the outcome of the forum discussion is to keep the custom allocator, it seems like we can keep VS2010 happy by changing the ```#ifdef``` to have VS2012 at the minimum?
```
#if defined(_MSC_VER) && _MSC_VER >= 1700 || !defined(_MSC_VER)
```
http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008

**Comment by The-E** [comment]
I am much more leaning towards not using the custom allocator anymore. If none of us really understand what it's doing, or even if it actually is doing useful things right now, that's a big fat warning to me.

**Comment by chief1983** [comment]
I thought that, as far as we could tell, the memory tracking was working correctly for SCP_* objects.  Disabling this for VS2010 was what I suggested last night but I won't argue that we need as I've never used the memory tracking.  Might ask the devs that have.

**Comment by MageKing17** [comment]
Now that SCP_vm_allocator has been removed, are there any remaining problems with this PR?

**Comment by niffiwan** [comment]
Not that I'm aware of, time for merging.
