### PR TITLE
Fix build issues with Vulkan SDK 1.3.301+

### LINKED ISSUE #6416: [24.2.0] fails to build with vulkan 1.3.301
24.2.0 fails to build with vulkan 1.3.301 with:
```
[...]
/var/tmp/paludis/build/games-simulation-fs2_open-24.2.0/work/fs2_open-24.2.0/code/graphics/vulkan/VulkanRenderer.cpp: In member function 'bool graphics::vulkan::VulkanRenderer::initializeSurface()':
/var/tmp/paludis/build/games-simulation-fs2_open-24.2.0/work/fs2_open-24.2.0/code/graphics/vulkan/VulkanRenderer.cpp:460:19: error: 'ObjectDestroy' in namespace 'vk' does not name a template type
  460 |         const vk::ObjectDestroy<vk::Instance, VULKAN_HPP_DEFAULT_DISPATCHER_TYPE> deleter(*m_vkInstance,
      |                   ^~~~~~~~~~~~~
/var/tmp/paludis/build/games-simulation-fs2_open-24.2.0/work/fs2_open-24.2.0/code/graphics/vulkan/VulkanRenderer.cpp:463:69: error: 'deleter' was not declared in this scope
  463 |         m_vkSurface = vk::UniqueSurfaceKHR(vk::SurfaceKHR(surface), deleter);
      |                                                                     ^~~~~~~

```
Complete build log: [fs2_open-24.2.0_build.log](https://github.com/user-attachments/files/17678860/fs2_open-24.2.0_build.log)

### PR DESCRIPTION
**Pull request by vmedea**
This fixes two build issues:

- `vk::PFN_DebugReportCallbackEXT` takes `vk::DebugReport*EXT` not C type `VkDebugReport*EXT` since version 1.3.304. (KhronosGroup/Vulkan-Hpp@d5a18dc87efbcc291bbd50a892187af4cbb60285)
- `vk::ObjectDestroy` was moved to namespace `vk::detail` in version 1.3.301. (KhronosGroup/Vulkan-Hpp@6e5489fcd96ba1e2cf994ebe3e4d1f5f4f690f4b)

Guard them with version checks, so that compiling with older verions of the Vulkan-Hpp headers keeps working.

Closes #6416.

### CODE REVIEW

**Review by Goober5000 — APPROVED** [review]
Nice work!
