### PR TITLE
Add API for registering custom event handler

### PR DESCRIPTION
**Pull request by asarium**
This is currently only used by the default event handlers but it could also be exposed to the scripting API or an external GUI framework.

### CODE REVIEW

**Comment by chief1983** [comment]
The appveyor failures now seem to be legitimate.  Different errors occurred in the different versions of VS as well, they'll need to be investigated.

**Comment by asarium** [comment]
Damnit VS2010! I guess using atomics without locking doesn't make much sense so I'll just remove it and add a note about thread safety.

The other issues are caused by the SDL2main library as that is somehow incompatible with our current setup.

**Comment by chief1983** [comment]
Didn't we just modify the setup to be compatible with VS 2015?

**Comment by asarium** [comment]
Yeah but I only have VS2015 so I couldn't update the other VS versions.

**Comment by asarium** [comment]
The last change should fix compilation on VS2010.

**Comment by chief1983** [comment]
According to AppVeyor, all VS builds failed the last go.  Try merging in master and kicking off another attempt?  Unless there's a good reason they failed, I didn't check the logs too closely.

**Comment by asarium** [comment]
They fail because they don't link the dialog files which causes a bunch of unresolved symbol errors but compilation is fine (I fixed a few issues to make sure I don't use features that VS2010 doesn't support).

**Comment by chief1983** [comment]
But then would merging this lead to broken AppVeyor checking again?  Guess I'm still confused as to whether these are false positives or what.

**Comment by asarium** [comment]
The errors are not really false positives as linking Antipodes is currently broken for everything that's not VS2015. Merging master wouldn't fix that as the files only got added to this branch.

**Comment by chief1983** [comment]
Right forgot this is antipodes based.

**Comment by asarium** [comment]
Rebased on current antipodes version to fix Windows link failures.

**Comment by asarium** [comment]
Fixed merge conflicts and compilation errors again.

**Comment by chief1983** [comment]
This waiting on anything then?

**Comment by MageKing17** [comment]
Will this conflict with PR #510?

**Comment by asarium** [comment]
Yes it will. I'll rebase this once #510 is merged (or the other way around).

**Comment by chief1983** [comment]
Maybe we should get this one and #442 merged if they're solid and then rebase #510 against the new master, and see if that helps with the failed Travis build.

**Comment by asarium** [comment]
That won't help with the compilation error because that's probably caused by an outdated compiler version.

**Comment by asarium** [comment]
Is there anything missing here or is this good to be merged?

File: code/io/joy-sdl.cpp [hunk 1]
```diff
@@ -145,6 +145,164 @@ namespace
...
+					state = (position == SDL_HAT_LEFT) ? 1 : 0;
+					break;
+				case JOY_HATRIGHT:
+					state = (position == SDL_HAT_RIGHT) ? 1 : 0;
+					break;
+				default:
+					break;
+			}
+
+			if (state != joy_buttons[i].actual_state) {
```
Comment (MageKing17) [inline code/io/joy-sdl.cpp]: This seems like a lot of duplicated code; could these two functions be merged, or maybe have this one call the other?

File: code/osapi/osapi.cpp [hunk 2]
```diff
@@ -314,142 +336,124 @@ void os_deinit()
...
-#endif // WIN32
-			break;
+			};
 
-		case SDL_KEYDOWN:
-			if (SDLtoFS2[event.key.keysym.scancode]) {
-				key_mark(SDLtoFS2[event.key.keysym.scancode], 1, 0);
-			}
-			break;
+			SCP_unordered_map<SDL_EventType, SCP_vector<EventListenerData>, enum_hash<SDL_EventType>> eventListeners;
```
Comment (MageKing17) [inline code/osapi/osapi.cpp]: What kind of performance impact does accessing a `std::unordered_map` for every event have?

File: code/io/joy-sdl.cpp (hunk 1 above)
Comment (asarium) [inline code/io/joy-sdl.cpp]: The code was copied from the previous event handling. I could probably improve the code but I would rather do that in a separate PR.

File: code/osapi/osapi.cpp [hunk 3]
```diff
@@ -314,142 +336,124 @@ void os_deinit()
...
+		}
+
+		ListenerIdentifier addEventListener(SDL_EventType type, int weigth, const Listener& listener)
```
Comment (MageKing17) [inline code/osapi/osapi.cpp]: Typo: `weigth`

File: code/sound/voicerec.cpp [hunk 4]
```diff
@@ -51,6 +54,27 @@ extern int Msg_instance;;
...
+	{
+		switch (e.syswm.msg->msg.win.msg)
+		{
+		case WM_RECOEVENT:
+			if (Game_mode & GM_IN_MISSION && Cmdline_voice_recognition)
+			{
+				VOICEREC_process_event(e.syswm.msg->msg.win.hwnd);
+				return true;
+			}
+			break;
```
Comment (MageKing17) [inline code/sound/voicerec.cpp]: Would it be worthwhile returning `true` here (to avoid wasting the time of anything outside the voice recognition with `WM_RECOEVENT`s just because -voicer is absent or we aren't in-game)?

File: code/io/joy-sdl.cpp (hunk 1 above)
Comment (MageKing17) [inline code/io/joy-sdl.cpp]: Fair enough; since the redundancy was in the original code, fixing it isn't necessarily within the scope of this PR.

File: code/osapi/osapi.cpp (hunk 2 above)
Comment (asarium) [inline code/osapi/osapi.cpp]: The impact should only be a bit higher than the switch-case variant. However, I could try using a vector with `std::sort` and `std::lower_bound`. That would trade runtime-complexity for better cache usage.
Honestly, I don't think it's worth the effort. The number of elements in the map will be pretty small so a map will still be pretty efficient.

File: code/sound/voicerec.cpp (hunk 4 above)
Comment (asarium) [inline code/sound/voicerec.cpp]: That wouldn't satisfy the requirements of an event handler. It's only supposed to return `true` if the event was actually handled which is not the case when `VOICEREC_process_event` wasn't called.

File: code/osapi/osapi.cpp (hunk 3 above)
Comment (asarium) [inline code/osapi/osapi.cpp]: Fixed.

**Comment by asarium** [comment]
I changed the implementation to use a vector instead of an unordered_map. It's reasonable simple to understand and probably performs better for the small vector sizes we have in this case.

**Comment by asarium** [comment]
These changes have been resubmitted in #662.
